### PR TITLE
add timeout to fix file monitor issue

### LINKED ISSUE #85: Time tracker logging time
I have been not able to use time tracking since I updated the extensions some 10 days ago. I had tried reinstalling/ resetting gnome multiple times and I still face this problem. I had this problem in gnome 3.28 and still have this problem in gnome 3.30. Had this problem in ubuntu 18.04 and 18.10 ( after updating )

This is how my `TODAY_time_tracker.csv` looks
```
raja@raja1:~/Documents/time++$ cat TODAY__time_tracker.csv 
2018-12-19, 00:00:00, ++, "+pnl", 20:27:27..20:27:27..
2018-12-19, 00:00:00, (), "2018-12-17 TT1815 +pnl ", 20:27:27..20:27:27..
raja@raja1:~/Documents/time++$ cat TODAY__time_tracker.csv 
2018-12-19, 00:00:00, ++, "+pnl", 20:27:29..20:27:29..
2018-12-19, 00:00:00, (), "2018-12-17 TT1815 +pnl ", 20:27:29..20:27:29..
raja@raja1:~/Documents/time++$ cat TODAY__time_tracker.csv 
2018-12-19, 00:00:00, ++, "+pnl", 20:27:30..20:27:30..
2018-12-19, 00:00:00, (), "2018-12-17 TT1815 +pnl ", 20:27:30..20:27:30..
raja@raja1:~/Documents/time++$ cat TODAY__time_tracker.csv 
2018-12-19, 00:00:00, ++, "+pnl", 20:27:34..20:27:34..
2018-12-19, 00:00:00, (), "2018-12-17 TT1815 +pnl ", 20:27:34..20:27:34..

```

When I turn off `restart after abrupt restart` I am not able to start timer for any tasks. If I leave it on, my start time and end time for the task gets updated to my current time. Find the log for `journalctl /usr/bin/gnome-shell -f -o cat` in this gist [here](https://gist.github.com/Rj7/708ce2d1769f8f27762f5e7570e8caa5)

Would really appreciate a fix / solution for this because I love this extension so much.

### PR DESCRIPTION
**Pull request by zexiangliu**
Attempt to fix #85. 

Potential issues not resolved by this pull request:
1. Based on the [doc of `timeout_add`](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add), callback function passed in timeout is repeatedly called.  But based on testings on my laptop, it is only called once. The code might need to call "source_remove" after using `timeout_add()`.

2. Based on testing, 100 ms timeout is not long enough for writing changes made by `_archive_daily_csv_file`. But it does not cause any issues on the user side.

### CODE REVIEW

File: sections/todo/time_tracker.js [hunk 1]
```diff
@@ -313,35 +316,65 @@ var TimeTracker  = class TimeTracker {
...
-
-        [this.yearly_csv_file_monitor,] = MISC_UTILS.file_monitor(this.yearly_csv_file, () => {
-            this._on_tracker_files_modified();
-        });
-
-        [this.yearly_csv_dir_monitor,] = MISC_UTILS.file_monitor(this.yearly_csv_dir, () => {
-            this._on_tracker_files_modified();
-        });
+    _enable_file_monitors (timeout = 100) {
+        try{
```
Comment (zagortenay333) [inline sections/todo/time_tracker.js]: That try-catch seems redundant to me.

File: sections/todo/time_tracker.js [hunk 2]
```diff
@@ -313,35 +316,65 @@ var TimeTracker  = class TimeTracker {
...
+                    this._on_tracker_files_modified();
+                    Main.notify('yearly csv dir is modified.')
+                });
+            });
+        }
+        catch (e){
+            logError(e);
+            _disable_file_monitors ();
+            if (this.daily_csv_file_monitor){
+                this.daily_csv_file_monitor.cancell();
```
Comment (zagortenay333) [inline sections/todo/time_tracker.js]: Typo in `cancell`.

Also, please add spaces between various symbols like braces to be consistent with the rest of the file.

File: sections/todo/time_tracker.js [hunk 3]
```diff
@@ -313,35 +316,65 @@ var TimeTracker  = class TimeTracker {
...
+            if (!this.yearly_csv_file_monitor){
+                this.yearly_csv_file_monitor = this.yearly_csv_file.monitor(Gio.FileMonitorFlags.NONE, null);
+            }
+    
+            if (!this.yearly_csv_dir_monitor){
+                this.yearly_csv_dir_monitor = this.yearly_csv_dir.monitor(Gio.FileMonitorFlags.NONE, null);
+            }
+    
+            Mainloop.timeout_add(timeout,()=>{
+                this.daily_csv_file_monitor_id = this.daily_csv_file_monitor.connect('changed', (...args) =>{
```
Comment (zagortenay333) [inline sections/todo/time_tracker.js]: Is there a reason you removed the `MISC_UTILS.file_monitor` call?

File: sections/todo/time_tracker.js [hunk 4]
```diff
@@ -313,35 +316,65 @@ var TimeTracker  = class TimeTracker {
...
+                    this._on_tracker_files_modified();
+                    Main.notify('daily_csv file is modified.')
+                });
+                this.yearly_csv_file_monitor_id = this.yearly_csv_file_monitor.connect('changed', (...args) =>{
+                    this._on_tracker_files_modified();
+                    Main.notify('yearly csv file is modified.')
```
Comment (zagortenay333) [inline sections/todo/time_tracker.js]: These notifications should be removed.

**Review by zagortenay333 — CHANGES_REQUESTED** [review]

File: sections/todo/time_tracker.js (hunk 1 above)
Comment (zexiangliu) [reply sections/todo/time_tracker.js]: It is not necessary. I used try-catch just because `MISC_UTILS.file_monitor` has a try-catch.

File: sections/todo/time_tracker.js (hunk 3 above)
Comment (zexiangliu) [reply sections/todo/time_tracker.js]: Instead of recreating a new file monitor, I think it enough to disconnect the file monitor when changes are made to file and then re-connect that to "changed" signal. This is not supported by `MISC_UTILS.file_monitor`. But one can probably make some modifications to `MISC_UTILS.file_monitor`.

Comment (zagortenay333) [reply sections/todo/time_tracker.js]: The function returns the monitor_id, so maybe the handler_block function can be used instead of disconnecting.

**Comment by zagortenay333** [comment]
Thx for the pull!
